/*
 * This program identifies the variables and values from the last line of a json data file (the type of "json" file that is generated by the ndt7 client of this project),
 and stores the list of identified values in a CSV file.
 The program appends to the output CSV file a line containing identified values separated by commas. The line is following by a newline
 so that more lines may be easily appended to the CSV file on subsequent readings of json data files.

 * The names of the input file and output file are read from the command line.
 * Syntax of running:
 * <executable> <input json data file> <output csv file>
 * For example,
 * ...$ ./extractCSV.out ndt7op.json datafile.csv

Written by Arunangshu Pal.
Tested OK. Running correctly. Thursday 16 October 2025 05:56:50 PM IST
Updated. Added timestamp (date and time) at the beginning of each csv line.
Tested OK. Running correctly. Wednesday 05 November 2025 05:01:42 PM 
 */

#include <iostream>
#include <fstream>
#include <cstring>
#define FNAMEMAX 100
#define JSONBLOCKMAX 1500
#define VARLEN 100
#define DATELEN 100
#define WRITESTRMAX JSONBLOCKMAX+DATELEN

using namespace std;

char *cleanWhites(char *);
char *strAppendCh(char *, char, int);
bool findSubstr(char *, char *);
char *extractCSV(char *, char *, int);
char *getDate(char *, int);

int main(int argc, char **argv)
{
	if(argc < 3)
	{
		cout<<"Give input file and output file as command-line arguments.\n";
		cout<<"Syntax:\n";
		cout<<"<executable> <input_filename> <output_filename>\n";
		cout<<"\nTerminating.\n";
		return 0;
	}

	char *fname1 = new char[FNAMEMAX];
	char *fname2 = new char[FNAMEMAX];
	strcpy(fname1, argv[1]);
	strcpy(fname2, argv[2]);

	ifstream ipfile;
	ipfile.open(fname1);
	ofstream opfile;
	opfile.open(fname2, ofstream::app);

	char *csvLine = new char[JSONBLOCKMAX];
	char *date = new char[DATELEN];
	char *writestr = new char[WRITESTRMAX];
	char *jsonblock = new char[JSONBLOCKMAX];
	char ch;

	if(ipfile.is_open() == false || opfile.is_open() == false)
		cout<<"File failed to open!\n";
	else
	{
		jsonblock[0] = '\0';
		int readmode = 0, jsonblockEnd = 0;
		do
		{
			ipfile.get(ch);
			if(ch == '{')
				readmode++;
			else if(ch == '}')
			{
				readmode--;
				if(readmode == 0)
					jsonblockEnd = 1;
			}

			if(readmode != 0)
				jsonblock = strAppendCh(jsonblock, ch, JSONBLOCKMAX);
			else
			{
				if(jsonblockEnd == 1)
				{
					jsonblock = strAppendCh(jsonblock, ch, JSONBLOCKMAX);
					ch = '\0';
					jsonblock = strAppendCh(jsonblock, ch, JSONBLOCKMAX);
					jsonblock = cleanWhites(jsonblock);
					bool dataLine;
					char *keyVar = new char[VARLEN];
					*keyVar = '\0';
					strcpy(keyVar, "\"ServerFQDN\"");
					dataLine = findSubstr(jsonblock, keyVar);
					if(dataLine == true)
					{
						csvLine = extractCSV(jsonblock, csvLine, JSONBLOCKMAX);
						getDate(date, DATELEN);
						*writestr = '\0';
						strcpy(writestr, date);
						ch = ',';
						strAppendCh(writestr, ch, WRITESTRMAX);
						writestr = strcat(writestr, csvLine);
						int len;
						len = strlen(writestr);
						opfile.write(writestr, len);
						char nl = '\n';
						opfile.put(nl);
					}
					jsonblock[0] = '\0';
					jsonblockEnd = 0;
					delete[] keyVar;
				}
			}
		}while(ipfile.eof() == false);
	}
	delete[] csvLine;
	delete[] date;
	delete[] writestr;
	delete[] jsonblock;
	delete[] fname1;
	delete[] fname2;
	
	ipfile.close();
	opfile.close();

	return 0;
}